/**
 * Turns a directory of 24×24 stroke SVGs into shape fragments for <Icon>.
 *
 * The kit's Icon already declares the viewBox, the stroke, the cap style and
 * the width, and any set drawn on the same contract declares exactly the same
 * things on its own <svg>. So adapting a set is subtraction: drop the wrapper,
 * keep the shapes. What is left inherits the kit's 1.6 stroke rather than the
 * 2 the source was drawn at, which is what makes the icons read lighter.
 *
 * A third argument additionally writes the same shapes as one sprite, for
 * everything outside this kit — static pages, another framework, the design file.
 *
 *   bun scripts/build-icons.ts <svg-dir> [out-file] [sprite-file]
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'

const [dir, out = 'src/icons.tsx', sprite] = process.argv.slice(2)
if (!dir) {
  console.error('usage: bun scripts/build-icons.ts <svg-dir> [out-file] [sprite-file]')
  process.exit(1)
}

/**
 * Only the source's own styling hook goes. Everything else on a shape is kept,
 * because on a shape the attributes that look presentational are not: `rect`
 * carries its size in `width`/`height`, and a `fill` on one circle out of three
 * is how a set draws a filled dot. The wrapper's copies of viewBox, stroke and
 * size never reach here — the scan matches shape elements, not the <svg>.
 */
const DROPPED = new Set(['class', 'className'])

const camel = (attr: string) => attr.replace(/-([a-z])/g, (_, c) => c.toUpperCase())

/** `chevron-down` → `chevronDown` */
const identifier = (file: string) =>
  basename(file, '.svg').replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

const warnings: string[] = []

function shapesOf(svg: string, file: string): string[] {
  const shapes: string[] = []

  for (const [, tag, rawAttrs] of svg.matchAll(
    /<(path|circle|rect|line|polyline|polygon)([^>]*)\/?>/g,
  )) {
    const attrs: string[] = []
    for (const [, name, value] of rawAttrs.matchAll(/([\w-]+)="([^"]*)"/g)) {
      if (DROPPED.has(name)) continue
      // Kept, but worth saying out loud: it beats the width Icon sets, so a set
      // that does this will not thin out with the rest of the kit.
      if (name === 'stroke-width')
        warnings.push(`${tag} in ${file}: stroke-width="${value}"`)
      attrs.push(`${camel(name)}="${value}"`)
    }
    shapes.push(`<${tag} ${attrs.join(' ')} />`)
  }

  return shapes
}

const files = readdirSync(dir)
  .filter((f) => f.endsWith('.svg'))
  .sort()

const entries = files.map((file) => {
  const shapes = shapesOf(readFileSync(join(dir, file), 'utf8'), file)
  if (shapes.length === 0) throw new Error(`no shapes in ${file}`)

  // A single shape stands on its own; several need a fragment to be one child.
  const body =
    shapes.length === 1 ? shapes[0] : `(\n  <>\n    ${shapes.join('\n    ')}\n  </>\n)`

  return `export const ${identifier(file)} = ${body}\n`
})

const header = `/* Generated by scripts/build-icons.ts — do not edit by hand.
   ${entries.length} shape fragments for <Icon>, stripped of their source wrapper.

     import { Icon, chevronDown } from 'creatox-ui-kit'
     <Icon>{chevronDown}</Icon>
*/\n\n`

writeFileSync(out, header + entries.join('\n'))
console.error(`${entries.length} иконок → ${out}`)

/**
 * The same shapes as one sprite, for everything that is not this React kit:
 * static pages, e-mail templates, another framework, the design file.
 *
 * Not the kit's own delivery mechanism, and deliberately so — `<use>` clones
 * into a shadow tree that CSS does not reliably inherit into, and inheritance
 * is the whole of Icon: colour comes from `currentColor`, size from `1em`. So
 * every symbol carries its own presentation attributes and stands alone.
 */
if (sprite) {
  const symbols = files.map((file) => {
    // No conversion back to kebab-case: shape attributes are single words
    // (d, cx, x1, width…), so nothing was camelised on the way in. Running a
    // camel→kebab pass over these would only risk chewing into path data.
    const shapes = shapesOf(readFileSync(join(dir, file), 'utf8'), file).join('')
    return (
      `  <symbol id="${basename(file, '.svg')}" viewBox="0 0 24 24" fill="none" ` +
      `stroke="currentColor" stroke-width="1.6" stroke-linecap="round" ` +
      `stroke-linejoin="round">${shapes}</symbol>`
    )
  })

  writeFileSync(
    sprite,
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join('\n')}\n</svg>\n`,
  )
  console.error(`${symbols.length} символов → ${sprite}`)
}
for (const w of warnings) console.error(`  внимание: ${w}`)
